-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2015-02-14 12:02:54.14
-- Source database is: sample
-- Connection URL is: jdbc:derby://localhost:1527/sample;user=thermospy;password=thermospy
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "THERMOSPY"."TEMPERATUREENTRY" ("ID" INTEGER NOT NULL, "TEMPERATURE" DOUBLE, "TIMESTAMP" TIMESTAMP NOT NULL, "FK_SESSION_ID" INTEGER);

CREATE TABLE "THERMOSPY"."CUT" ("ID" INTEGER NOT NULL, "NAME" VARCHAR(20));

CREATE TABLE "THERMOSPY"."SESSION" ("ID" INTEGER NOT NULL, "FK_FOODTYPE_ID" INTEGER, "FK_CUT_ID" INTEGER, "NAME" VARCHAR(50), "START_TIMESTAMP" TIMESTAMP, "END_TIMESTAMP" TIMESTAMP, "COMMENT" LONG VARCHAR);

CREATE TABLE "THERMOSPY"."FOODTYPE" ("ID" INTEGER NOT NULL, "NAME" VARCHAR(20));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "THERMOSPY"."CUT" ADD CONSTRAINT "SQL150213182006460" PRIMARY KEY ("ID");

ALTER TABLE "THERMOSPY"."FOODTYPE" ADD CONSTRAINT "SQL150213181848820" PRIMARY KEY ("ID");

ALTER TABLE "THERMOSPY"."TEMPERATUREENTRY" ADD CONSTRAINT "SQL150213181304160" PRIMARY KEY ("ID");

ALTER TABLE "THERMOSPY"."SESSION" ADD CONSTRAINT "SQL150213183523380" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "THERMOSPY"."TEMPERATUREENTRY" ADD CONSTRAINT "SQL150213183811550" FOREIGN KEY ("FK_SESSION_ID") REFERENCES "THERMOSPY"."SESSION" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "THERMOSPY"."SESSION" ADD CONSTRAINT "SQL150213183617710" FOREIGN KEY ("FK_CUT_ID") REFERENCES "THERMOSPY"."CUT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "THERMOSPY"."SESSION" ADD CONSTRAINT "SQL150213183607990" FOREIGN KEY ("FK_FOODTYPE_ID") REFERENCES "THERMOSPY"."FOODTYPE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;


-- INSERT DEFAULT DATA
insert into THERMOSPY.FOODTYPE values (1, 'None'); 
insert into THERMOSPY.CUT values (1, 'None'); 
