package com.luan.thermospy.server.db;
// Generated 2015-feb-14 09:17:56 by Hibernate Tools 4.3.1



/**
 * Foodtype generated by hbm2java
 */
public class Foodtype  implements java.io.Serializable {


     private int id;
     private String name;

    public Foodtype() {
    }

	
    public Foodtype(int id) {
        this.id = id;
    }
    public Foodtype(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


