package com.luan.thermospy.server.db;
// Generated 2015-feb-14 09:17:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private int id;
     private Integer fkFoodtypeId;
     private Integer fkCutId;
     private String name;
     private Date startTimestamp;
     private Date endTimestamp;
     private String comment;

    public Session() {
    }

	
    public Session(int id) {
        this.id = id;
    }
    public Session(int id, Integer fkFoodtypeId, Integer fkCutId, String name, Date startTimestamp, Date endTimestamp, String comment) {
       this.id = id;
       this.fkFoodtypeId = fkFoodtypeId;
       this.fkCutId = fkCutId;
       this.name = name;
       this.startTimestamp = startTimestamp;
       this.endTimestamp = endTimestamp;
       this.comment = comment;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getFkFoodtypeId() {
        return this.fkFoodtypeId;
    }
    
    public void setFkFoodtypeId(Integer fkFoodtypeId) {
        this.fkFoodtypeId = fkFoodtypeId;
    }
    public Integer getFkCutId() {
        return this.fkCutId;
    }
    
    public void setFkCutId(Integer fkCutId) {
        this.fkCutId = fkCutId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartTimestamp() {
        return this.startTimestamp;
    }
    
    public void setStartTimestamp(Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }
    public Date getEndTimestamp() {
        return this.endTimestamp;
    }
    
    public void setEndTimestamp(Date endTimestamp) {
        this.endTimestamp = endTimestamp;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


