package com.luan.thermospy.server.db;
// Generated 2015-feb-14 09:17:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Temperatureentry generated by hbm2java
 */
public class Temperatureentry  implements java.io.Serializable {


     private int id;
     private Date timestamp;
     private Double temperature;
     private Integer fkSessionId;

    public Temperatureentry() {
    }

	
    public Temperatureentry(int id) {
        this.id = id;
    }
    public Temperatureentry(int id, Double temperature, Integer fkSessionId) {
       this.id = id;
       this.temperature = temperature;
       this.fkSessionId = fkSessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Double getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }
    public Integer getFkSessionId() {
        return this.fkSessionId;
    }
    
    public void setFkSessionId(Integer fkSessionId) {
        this.fkSessionId = fkSessionId;
    }




}


